name: 'git-archive-all'
author: 'Jayrgo'

inputs:
  output:
    required: true
  args:
    description: 'Arguments passed to git-archive-all.'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install git-archive-all
      run: sudo pip install git-archive-all
      shell: bash
    - name: Luacheck
      run: git-archive-all ${{ inputs.args }} ${{ inputs.output }}
      shell: bash
